export const PUSH_ROUTE = 'PUSH_ROUTE';
export const POP_ROUTE = 'POP_ROUTE';
export const CHANGE_TAB = 'CHANGE_TAB';
export const AUTH_PUSH_ROUTE = 'AUTH_PUSH_ROUTE';
export const AUTH_POP_ROUTE = 'AUTH_POP_ROUTE';
export const GET_COUPON_INFO = 'GET_COUPON_INFO';

export const REQUEST_COUPONS = 'REQUEST_COUPONS';
export const RECEIVE_COUPONS = 'RECEIVE_COUPONS';

export const REQUEST_SINGLE_COUPON = 'REQUEST_SINGLE_COUPON';
export const RECEIVE_SINGLE_COUPON = 'RECEIVE_SINGLE_COUPON';
