export const PUSH_ROUTE = 'PUSH_ROUTE';
export const POP_ROUTE = 'POP_ROUTE';
export const CHANGE_TAB = 'CHANGE_TAB';
export const AUTH_PUSH_ROUTE = 'AUTH_PUSH_ROUTE';
export const AUTH_POP_ROUTE = 'AUTH_POP_ROUTE';
export const GET_COUPON_INFO = 'GET_COUPON_INFO';

export const REQUEST_COUPONS = 'REQUEST_COUPONS';
export const RECEIVE_COUPONS = 'RECEIVE_COUPONS';

export const REQUEST_SINGLE_COUPON = 'REQUEST_SINGLE_COUPON';
export const RECEIVE_SINGLE_COUPON = 'RECEIVE_SINGLE_COUPON';

export const REQUEST_AUTH = 'REQUEST_AUTH';
export const RECEIVE_AUTH = 'RECEIVE_AUTH';
export const RECEIVE_FAILED_AUTH = 'RECEIVE_FAILED_AUTH';

export const REQUEST_USER_INFO_BY_DEVICE = 'REQUEST_USER_INFO_BY_DEVICE';
export const RECEIVE_USER_INFO_BY_DEVICE = 'RECEIVE_USER_INFO_BY_DEVICE';

export const REQUEST_NEWUSER = 'REQUEST_NEWUSER';
export const RECEIVE_NEWUSER = 'RECEIVE_NEWUSER';

export const REQUEST_USE_COUPON = 'REQUEST_USE_COUPON';
export const RECEIVE_USE_COUPON = 'RECEIVE_USE_COUPON';