export const USER_LOGOUT = 'USER_LOGOUT';

export const PUSH_ROUTE = 'PUSH_ROUTE';
export const POP_ROUTE = 'POP_ROUTE';

export const CHANGE_TAB = 'CHANGE_TAB';

export const LISTEN_BEACON = 'LISTEN_BEACON';
export const BEACON_REQUEST_COUPONS = 'BEACON_REQUEST_COUPONS';
export const BEACON_RECEIVE_COUPONS = 'BEACON_RECEIVE_COUPONS';

export const AUTH_PUSH_ROUTE = 'AUTH_PUSH_ROUTE';
export const AUTH_POP_ROUTE = 'AUTH_POP_ROUTE';
export const GET_COUPON_INFO = 'GET_COUPON_INFO';

export const REQUEST_COUPONS = 'REQUEST_COUPONS';
export const RECEIVE_COUPONS = 'RECEIVE_COUPONS';
export const SORT_BY_DATE = 'SORT_BY_DATE';
export const SORT_BY_TIME_LEFT = 'SORT_BY_TIME_LEFT';
export const SORT_BY_SAVINGS = 'SORT_BY_SAVINGS';
// export const SORT_BY_USED = 'SORT_BY_USED';
// export const SORT_BY_EXPIRED = 'SORT_BY_EXPIRED';
// export const SORT_BY_ACTIVATED = 'SORT_BY_ACTIVATED';

export const REQUEST_SINGLE_COUPON = 'REQUEST_SINGLE_COUPON';
export const RECEIVE_SINGLE_COUPON = 'RECEIVE_SINGLE_COUPON';

export const REQUEST_AUTH = 'REQUEST_AUTH';
export const RECEIVE_AUTH = 'RECEIVE_AUTH';
export const RECEIVE_FAILED_AUTH = 'RECEIVE_FAILED_AUTH';

export const REQUEST_USER_INFO_BY_DEVICE = 'REQUEST_USER_INFO_BY_DEVICE';
export const RECEIVE_USER_INFO_BY_DEVICE = 'RECEIVE_USER_INFO_BY_DEVICE';

export const REQUEST_NEWUSER = 'REQUEST_NEWUSER';
export const RECEIVE_NEWUSER = 'RECEIVE_NEWUSER';

export const REQUEST_USE_COUPON = 'REQUEST_USE_COUPON';
export const RECEIVE_USE_COUPON = 'RECEIVE_USE_COUPON';

export const REQUEST_PASSWORDINFO = 'REQUEST_PASSWORDINFO';
export const RECEIVE_PASSWORDINFO = 'RECEIVE_PASSWORDINFO';
export const RECEIVE_FAILED_PASSWORDINFO = 'RECEIVE_FAILED_PASSWORDINFO';
